name: Mermaid

on:
  push:
    branches: [ main ]
    paths:
      - action.yml
  workflow_dispatch:

permissions:
  contents: write

jobs:
  mermaid:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - id: mermaid
        uses: imjohnbo/action-to-mermaid@a55b587b59c381f5f3becdbc1992988a766f2139 # v1

      # Create or update an action.mermaid.md
      - name: Create or update action.mermaid.md
        env:
          MERMAID: ${{ steps.mermaid.outputs.mermaid }}
        run: |-
          echo "$MERMAID" > action.mermaid.md
          
      - name: Create or update mermaid section of README
        env:
          MERMAID: ${{ steps.mermaid.outputs.mermaid }}
        run: |-
          echo 'f = File.read("README.md")' >> script.rb
          echo 'f = f.sub(/(<!-- START MERMAID -->).*(<!-- END MERMAID -->)/im, "<!-- START MERMAID -->\n#{ENV["MERMAID"]}\n<!-- END MERMAID -->")' >> script.rb
          echo 'File.write("README.md", f, mode: "w")' >> script.rb
          ruby script.rb

      - name: Commit to action.mermaid.md
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: imjohnbo/commit@178d297eaefad8461c6d8517e6a7e62ae0c9d45c # v1
        with:
          files: |
            action.mermaid.md
            README.md
          commit-message: Update action.mermaid.md with mermaid diagram
          ref: refs/heads/main
