name: Publish

on:
  release:
    types: [published, edited]
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          ref: ${{ github.event.release.tag_name }}
          
      - uses: JasonEtco/build-and-tag-action@5220ac2e69814ad86f9139a33d4f2de17c2272ea # v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
